{\rtf1\ansi\ansicpg1252\cocoartf2757
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red224\green233\blue240;\red224\green232\blue240;
}
{\*\expandedcolortbl;;\cssrgb\c0\c1\c1;\cssrgb\c90313\c93062\c95303;\cssrgb\c90196\c92941\c95294;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs27\fsmilli13600 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec3 remote_theme: pages-themes/minimal@v0.2.0\
plugins:\
- jekyll-remote-theme\cf4 \strokec4 \
}